/* oracle_diff — run the same guest function through the interpreter and the
 * recompiled C, and report where they disagree.
 *
 * This is the tier-1 oracle from docs/ORACLE.md. A game's build compiles it
 * with that game's generated C, whose psp_recomp_register it calls; it was
 * written against Armored Core: Last Raven, whose repository carried it until
 * it moved here. The two sides share their decoder, CPU state, memory model and
 * semantic helpers; the only thing that differs is that one sequences
 * instructions itself and the other runs emitted control flow. So a divergence
 * localises to the emitter or to the interpreter's sequencing, and nowhere
 * else. That narrowing is the entire value.
 *
 * Method, per function: build a deterministic starting state, snapshot it, run
 * one side, capture the result, restore, run the other, compare.
 *
 * Firmware calls used to be excluded: the recompiled stub called psp_hle_call()
 * while the interpreter ran the unlinked `jr $ra` still sitting in the module,
 * so the two disagreed at every import by construction. The interpreter now
 * routes thunk hits into HLE as well (psp_interp_set_imports), and both sides
 * cross the boundary identically.
 *
 * Two things are still excluded:
 *
 *   Guest re-entry from HLE. A few handlers call back into guest code — a
 *   thread entry point, a registered callback — through psp_dispatch(), which
 *   only knows about *recompiled* functions. On the interpreter's side of the
 *   comparison that would quietly run recompiled code, so the run is no longer
 *   independent and the result proves nothing. Detected by watching the
 *   dispatch counter and skipped.
 *
 *   Traps. Either side may hit an unimplemented instruction. A trap on both
 *   sides at the same place is agreement, not a finding.
 */

#include "interp.h"
#include "decode.h"
#include "container.h"
#include "loader.h"

#include "psprecomp/cpu.h"
#include "psprecomp/mem.h"
#include "psprecomp/dispatch.h"
#include "psprecomp/hle.h"
#include "psprecomp/clock.h"
#include "psprecomp/sched.h"

#include <setjmp.h>
#include <signal.h>
#include <unistd.h>
#include <sys/time.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Generated by allegrexrecomp; declared here so the harness does not depend on
 * a particular emit prefix being on the include path. */
void psp_recomp_register(void);

/* The function's stack, taken from the allocator in reset_hle like any other
 * block, so that a thread stack or a high allocation the function makes lands
 * below it rather than on its frame. It used to sit unreserved 4 KiB under the
 * end of RAM, where sysmem's high blocks start, and the 0xFF fill
 * sceKernelStartThread paints on a new thread's stack landed on the frame
 * being compared: Last Raven's oracle reported 0x0001093C and 0x00195654 with
 * interp=00000000 recomp=FFFFFFFF in $s0 and $s1, and 361 of its runs spun in
 * libc's exit loop until the budget ran out, where 7 do now. Both functions
 * still differ, in the first word of that thread's stack block and, for
 * 0x0001093C, in module word 0: each starts a thread and waits for it, which
 * the two sides do not yet run alike. The allocator is reset to the same
 * state before each side, so both get the same block. */
#define ORACLE_STACK 0x100000u
static uint32_t g_stack_top;
#define RA_DONE    0x0DEAD000u
/* Where seeded pointer arguments point: RAM, well clear of the stack. */
#define ARG_ARENA  (PSP_RAM_BASE + 0x00400000u)
/* Sized from the largest genuine run observed: a module initialiser that sorts
 * 3,420 entries and returns after 915,297 instructions. The original 200k
 * ceiling reported that as a hang; 4M was the first guess after, and it cost
 * more than it bought -- with relocations applied, half the corpus reaches real
 * `memset` calls whose sizes now come from the data segment rather than reading
 * as null, and each one burns the whole budget before being discarded anyway.
 * 1.2M keeps the known-good case with margin and cuts a corpus run roughly
 * fourfold. Anything above it is recorded as budget-exhausted, which is honest:
 * the harness did not evaluate it. */
#define INTERP_BUDGET  1200000u

/* ---- trap capture ---------------------------------------------------------
 *
 * The recompiled path reports an untranslatable instruction by calling
 * psp_unimplemented(), which a real host would make fatal. Here it has to be
 * survivable: the harness wants to note "this side trapped" and move on to the
 * next function, not take the process down. longjmp is the only way back out
 * of generated code, which has no error return of its own. */

static sigjmp_buf g_trap;
static int        g_trapped;      /* 1 = trap, 2 = watchdog timeout */
static uint32_t   g_trap_addr;
static const char *g_trap_what;

void psp_unimplemented(uint32_t addr, const char *what) {
    g_trapped = 1; g_trap_addr = addr; g_trap_what = what;
    siglongjmp(g_trap, 1);
}

/* Why runs stop, tallied by reason. "trapped" was one bucket holding several
 * unrelated things -- an unimplemented instruction, a syscall, and an
 * instruction budget that simply ran out -- which made the largest category in
 * the report also the least informative. They want different fixes. */
#define TALLY_MAX 64
typedef struct { char name[48]; long n; } tally_row;
static tally_row g_why[TALLY_MAX];
static int g_nwhy;

static void tally(const char *name) {
    for (int i = 0; i < g_nwhy; i++)
        if (!strcmp(g_why[i].name, name)) { g_why[i].n++; return; }
    if (g_nwhy == TALLY_MAX) return;
    snprintf(g_why[g_nwhy].name, sizeof g_why[0].name, "%s", name);
    g_why[g_nwhy].n = 1;
    g_nwhy++;
}

/* For a run that exhausts its budget, the interesting question is not that it
 * looped -- it is what it was waiting for. Recording which firmware call the
 * run made most names the blocker directly: a spin on an unimplemented
 * function that keeps returning zero looks exactly like this. */
static void tally_dump(void) {
    for (int i = 1; i < g_nwhy; i++) {          /* insertion sort, descending */
        tally_row t = g_why[i];
        int j = i - 1;
        while (j >= 0 && g_why[j].n < t.n) { g_why[j + 1] = g_why[j]; j--; }
        g_why[j + 1] = t;
    }
    printf("\nwhy runs stopped early:\n");
    for (int i = 0; i < g_nwhy; i++)
        printf("  %-34s %8ld\n", g_why[i].name, g_why[i].n);
}

void psp_syscall(uint32_t id) {
    g_trapped = 1; g_trap_addr = id; g_trap_what = "syscall";
    siglongjmp(g_trap, 1);
}

/* The interpreter stops itself at an instruction budget. The recompiled side
 * has no such control: it is ordinary C, and a function that loops forever
 * loops forever. That is not hypothetical — the harness hung on it — and it is
 * also interesting, because the interpreter having *returned* from the same
 * function on the same input means the two disagree about termination.
 *
 * So: a wall-clock watchdog. Jumping out of a signal handler is not something
 * to do in shipped code, but this is a development harness and the alternative
 * is no result at all. */
/* psp_dispatch's default miss handler aborts. That is right for a real host and
 * wrong here: the seeded argument registers mean an HLE handler can be handed a
 * garbage function pointer and try to dispatch on it, which is a property of
 * the test inputs rather than a defect. Record and continue; the caller treats
 * any dispatch activity during an interpreter run as grounds to skip. */
static uint64_t g_miss_count;

/* Phase markers for diagnosing a hang. write(2) rather than stdio: this has to
 * work when the question is whether stdio itself is wedged. */
static int g_phase_trace;
static int want_profile;   /* --profile: per-instruction PC histogram */
static void phase(const char *tag) {
    if (g_phase_trace) { write(2, "[", 1); write(2, tag, strlen(tag)); write(2, "]\n", 2); }
}

static void note_miss(uint32_t addr) {
    (void)addr;
    g_miss_count++;
}

/* Guest re-entry from an HLE handler, stopped at the source.
 *
 * During the interpreter's run, psp_dispatch() must not run recompiled code:
 * it would destroy this side's independence, and -- because native code has no
 * instruction budget -- it can simply never come back. Detecting the re-entry
 * afterwards, which is what the dispatch counter does, cannot prevent that; the
 * run has already hung by the time anyone looks.
 *
 * A dispatch budget of zero turns the first such call into an immediate exit
 * instead. Relocating the module made this urgent rather than academic: guest
 * code now reaches real thread-creation and callback paths, so handlers re-enter
 * far more often than they did when every pointer read as null. */
static void on_reentry(void) {
    g_trapped = 4;
    siglongjmp(g_trap, 1);
}

static void watchdog(int sig) {
    (void)sig;
    g_trapped = 2;
    siglongjmp(g_trap, 1);
}

/* Recompiled guest code is ordinary C running on the host stack, and every
 * guest call is a real call. A deep or mutually recursive guest chain -- easy
 * to reach from seeded argument registers -- overflows that stack and the
 * process dies with SIGSEGV, taking the whole corpus run with it. Both full
 * runs stopped at the same function for this reason.
 *
 * Catching it needs an alternate signal stack, because by the time the fault
 * arrives the normal one has no room left to run a handler on. Treated as a
 * skip: it says the harness cannot evaluate this function, not that the two
 * sides disagree. */
static void faulted(int sig) {
    (void)sig;
    g_trapped = 3;
    siglongjmp(g_trap, 1);
}

static void install_fault_handler(void) {
    static char altstack[SIGSTKSZ < 65536 ? 65536 : SIGSTKSZ];
    stack_t ss = { .ss_sp = altstack, .ss_size = sizeof altstack, .ss_flags = 0 };
    sigaltstack(&ss, NULL);

    struct sigaction sa;
    memset(&sa, 0, sizeof sa);
    sa.sa_handler = faulted;
    sa.sa_flags   = SA_ONSTACK | SA_NODEFER;
    sigemptyset(&sa.sa_mask);
    sigaction(SIGSEGV, &sa, NULL);
    sigaction(SIGBUS,  &sa, NULL);
    /* The runtime aborts on some unrecoverable paths, and a stack-protector
     * trip lands here too. Same treatment: this function cannot be
     * evaluated, the rest of the corpus still can. */
    sigaction(SIGABRT, &sa, NULL);
}

/* alarm(2) was the first attempt and made a 400-function run take longer than
 * ten minutes: once firmware calls started doing real work, far more functions
 * ran long enough to reach the timeout, and each one then cost a full two
 * seconds of wall clock. setitimer gives sub-second granularity. A function
 * the interpreter finished in under 200k instructions has no business taking
 * this long as native code. */
/* Asymmetric on purpose. The interpreter bounds itself by instruction count,
 * so its watchdog is only a backstop against an HLE handler that re-enters
 * guest code and never comes back -- it can afford to be generous, and once
 * the module is relocated real functions genuinely run millions of
 * instructions. The recompiled side has no self-bound at all: it is ordinary C,
 * and a loop that does not terminate does not terminate. That one stays tight. */
#define WATCHDOG_INTERP_USEC  2000000
#define WATCHDOG_RECOMP_USEC   200000

static void watchdog_arm_us(long usec) {
    struct itimerval t = {{0, 0}, {0, usec}};
    setitimer(ITIMER_REAL, &t, NULL);
}

static void watchdog_arm(void) { watchdog_arm_us(WATCHDOG_RECOMP_USEC); }

static void watchdog_disarm(void) {
    struct itimerval t = {{0, 0}, {0, 0}};
    setitimer(ITIMER_REAL, &t, NULL);
}

/* ---- state snapshots ------------------------------------------------------
 *
 * Comparing the register file alone would miss the whole class of bugs where a
 * function computes the right answer into the wrong address, so memory is
 * compared too.
 *
 * Two regions carry the state a function under test can reach: all of RAM,
 * which holds its stack, and the module image -- code and the data segment,
 * mapped at the link address and kept apart from RAM. The snapshot's `stack`
 * names the RAM copy, after the window it once was. */

/* Full RAM. A narrower window was tried and was wrong: functions here reach
 * memory through globals in the data segment, so a write can land anywhere in
 * RAM. Restoring only a stack window left those writes visible to the second
 * run, which manufactured divergences that looked exactly like codegen bugs.
 * Correctness first; this costs about 30 ms per function. */
#define STACK_WIN_LEN  PSP_RAM_SIZE
#define STACK_WIN_OFF  0u

typedef struct {
    psp_cpu_state cpu;
    uint8_t      *stack;
    uint8_t      *module;
    uint64_t      bad_access;
} snapshot;

static uint8_t *g_module_host;
static uint32_t g_module_lo, g_module_size;

static void snap_alloc(snapshot *s) {
    s->stack  = malloc(STACK_WIN_LEN);
    s->module = malloc(g_module_size);
    if (!s->stack || !s->module) { fprintf(stderr, "out of memory\n"); exit(1); }
}

static void snap_take(snapshot *s) {
    s->cpu = psp_cpu;
    memcpy(s->stack,  psp_mem.ram + STACK_WIN_OFF, STACK_WIN_LEN);
    memcpy(s->module, g_module_host, g_module_size);
    s->bad_access = psp_mem_bad_access;
}

static void snap_restore(const snapshot *s) {
    psp_cpu = s->cpu;
    memcpy(psp_mem.ram + STACK_WIN_OFF, s->stack,  STACK_WIN_LEN);
    psp_mem_mark_write(PSP_RAM_BASE + STACK_WIN_OFF, STACK_WIN_LEN);
    memcpy(g_module_host, s->module, g_module_size);
    psp_mem_mark_write(g_module_lo, g_module_size);
    psp_mem_bad_access = s->bad_access;
}

/* Reset the HLE layer's own state.
 *
 * The snapshot covers psp_cpu, RAM and the module image -- but the firmware
 * layer keeps state in ordinary C statics that none of those reach: the
 * allocator's block table and next-uid counter, the thread table, GE and
 * display registers. Left alone, the interpreter's allocations persist into the
 * recompiled run, which then gets *different addresses back* from the same
 * calls.
 *
 * That shows up as small, plausible-looking differences in stored pointers --
 * `interp=0400C000 recomp=0400C200` against a VRAM base -- which reads exactly
 * like a codegen bug and is not one. Both sides have to start from the same
 * firmware state as well as the same machine state. */
static void reset_hle(void) {
    psp_sysmem_reset();
    psp_threadman_reset();
    psp_display_reset();
    psp_ge_reset();
    psp_sas_reset();
    psp_io_reset();
    psp_misc_reset();
    /* The clock is firmware state too, and it was the one piece not reset here.
     * It advances on every read -- and now on every firmware call -- so without
     * this the second side of a comparison starts at whatever time the first
     * side ran up to, and any guest code that branches on elapsed time diverges
     * for a reason that is not codegen. Exactly the failure the comment above
     * describes for allocator addresses, in a different currency. */
    psp_clock_reset();

    const uint32_t stack = psp_sysmem_alloc(ORACLE_STACK, 1);
    if (!stack) { fprintf(stderr, "cannot allocate the oracle's stack\n"); exit(1); }
    g_stack_top = (stack + ORACLE_STACK - 64) & ~15u;
}

/* ---- deterministic starting state -----------------------------------------
 *
 * Argument registers get pseudo-random values so the comparison exercises real
 * data paths rather than the all-zero case, which hides sign handling and
 * masks whole branches. The generator is a plain LCG seeded from the function
 * address: identical every run, so a divergence can be reproduced exactly.
 *
 * The values are kept small and non-negative. Wild pointers would send both
 * sides into unmapped memory, where they agree trivially (reads return 0) and
 * the test proves nothing. */

static void seed_state(uint32_t addr) {
    memset(&psp_cpu, 0, sizeof psp_cpu);
    uint32_t x = addr * 1103515245u + 12345u;
    /* Argument registers get RAM addresses, not small integers.
     *
     * Small values were the obvious choice and were wrong: the module is mapped
     * at 0, so 0x0..0x3FFF is *inside .text*. A function that treats an
     * argument as a pointer and stores through it then overwrites its own code
     * -- and at that point the two sides diverge by construction, because the
     * interpreter fetches instructions from memory and runs the corrupted
     * version while the recompiled C was fixed at compile time. That is
     * self-modifying code, not a codegen bug, but it reads exactly like one.
     *
     * Pointing them into RAM keeps stores away from the code segment. */
    /* $a0 and $a1 as pointers, $a2 and $a3 as small counts.
     *
     * Making all four pointers was the previous attempt and traded one problem
     * for another: for the very common (dst, src_or_value, length) shape, the
     * length argument became a RAM address, so a memset-like function looped
     * about 138 million times and exhausted the instruction budget. That does
     * not test the recompiler, it tests how long the harness will wait.
     *
     * Neither split is right for every function -- nothing is, without knowing
     * each signature -- but this one matches the dominant MIPS calling shape
     * and keeps both the pointers valid and the counts sane. */
    for (int i = 4; i <= 5; i++) {          /* $a0, $a1 -- pointers */
        x = x * 1103515245u + 12345u;
        psp_cpu.r[i] = ARG_ARENA + (((x >> 16) & 0x3FF) * 64);
    }
    for (int i = 6; i <= 7; i++) {          /* $a2, $a3 -- counts */
        x = x * 1103515245u + 12345u;
        psp_cpu.r[i] = (x >> 16) & 0xFF;
    }
    for (int i = 8; i <= 15; i++) {         /* $t0..$t7 */
        x = x * 1103515245u + 12345u;
        psp_cpu.r[i] = (x >> 16) & 0x3FFF;
    }
    psp_cpu.r[PSP_REG_SP] = g_stack_top;
    psp_cpu.r[PSP_RA_INDEX] = RA_DONE;
}

/* ---- comparison ----------------------------------------------------------- */

/* Callee-saved registers plus the return values are what a caller can observe.
 * $t0-$t9 and $a0-$a3 are caller-saved: the two sides are entitled to leave
 * different garbage there, and comparing them produces noise, not findings. */
static int reg_is_observable(int i) {
    if (i == PSP_REG_V0 || i == PSP_REG_V1) return 1;         /* returns */
    if (i >= PSP_REG_S0 && i <= PSP_REG_S7) return 1;         /* callee-saved */
    if (i == PSP_REG_SP || i == PSP_REG_FP || i == PSP_REG_GP) return 1;
    return 0;
}

static int compare(const snapshot *a, const snapshot *b, uint32_t addr, int verbose) {
    int diffs = 0;

    for (int i = 0; i < PSP_NUM_GPR; i++) {
        if (!reg_is_observable(i)) continue;
        if (a->cpu.r[i] != b->cpu.r[i]) {
            if (verbose || diffs < 4)
                printf("  %08X  $%-4s interp=%08X recomp=%08X\n",
                       addr, psp_reg_names[i], a->cpu.r[i], b->cpu.r[i]);
            diffs++;
        }
    }
    if (a->cpu.hi != b->cpu.hi) { printf("  %08X  hi   interp=%08X recomp=%08X\n",
                                         addr, a->cpu.hi, b->cpu.hi); diffs++; }
    if (a->cpu.lo != b->cpu.lo) { printf("  %08X  lo   interp=%08X recomp=%08X\n",
                                         addr, a->cpu.lo, b->cpu.lo); diffs++; }

    if (memcmp(a->stack, b->stack, STACK_WIN_LEN) != 0) {
        for (uint32_t o = 0; o < STACK_WIN_LEN; o += 4) {
            if (memcmp(a->stack + o, b->stack + o, 4) == 0) continue;
            printf("  %08X  stack[%08X] interp=%02X%02X%02X%02X recomp=%02X%02X%02X%02X\n",
                   addr, PSP_RAM_BASE + STACK_WIN_OFF + o,
                   a->stack[o+3], a->stack[o+2], a->stack[o+1], a->stack[o],
                   b->stack[o+3], b->stack[o+2], b->stack[o+1], b->stack[o]);
            diffs++;
            break;
        }
    }
    if (memcmp(a->module, b->module, g_module_size) != 0) {
        /* Report where, not just that. "module image differs" is unactionable:
         * the offset says whether this is a data-segment global, a write
         * through a wild pointer, or code being overwritten. */
        uint32_t first = 0;
        int shown = 0;
        for (uint32_t o = 0; o + 4 <= g_module_size; o += 4) {
            if (memcmp(a->module + o, b->module + o, 4) == 0) continue;
            first = o;
            printf("  %08X  module[%08X] interp=%02X%02X%02X%02X recomp=%02X%02X%02X%02X\n",
                   addr, g_module_lo + o,
                   a->module[o+3], a->module[o+2], a->module[o+1], a->module[o],
                   b->module[o+3], b->module[o+2], b->module[o+1], b->module[o]);
            shown = 1;
            break;
        }
        if (!shown) printf("  %08X  module image differs\n", addr);
        (void)first;
        diffs++;
    }
    return diffs;
}

/* ---- one function --------------------------------------------------------- */

typedef enum { R_MATCH, R_DIFF, R_SKIP_IMPORT, R_SKIP_NOFN, R_SKIP_TRAP, R_HANG, R_SKIP_UNBALANCED, R_SKIP_REENTRY, R_HANG_INTERP, R_FAULT, R_DIFF_MISS } result;

static uint32_t g_stub_lo, g_stub_hi;

static snapshot g_pristine;   /* the loaded module, before anything ran */

static result check_one(uint32_t addr, snapshot *base, snapshot *si, snapshot *sr,
                        int verbose) {
    psp_fn_t fn = psp_lookup(addr);
    if (!fn) return R_SKIP_NOFN;

    /* Start every function from the freshly-loaded image, not from whatever the
     * previous one left behind. Without this the harness is order-dependent:
     * each function inherits the last one's writes, memory degrades as the run
     * goes on, and later functions start reading code as data. That shows up as
     * registers holding MIPS instruction words -- which looks exactly like a
     * codegen bug and is not one. */
    snap_restore(&g_pristine);
    reset_hle();

    seed_state(addr);
    snap_take(base);

    /* --- interpreter --- */
    psp_interp it;
    psp_interp_init(&it, addr, RA_DONE, INTERP_BUDGET);
    psp_interp_hle_reset();
    if (want_profile) psp_interp_profile_reset();
    psp_interp_hle_reset();

    /* Thunk hits now go through HLE inside psp_interp_step, so the stub region
     * is no longer a stopping condition. What still is: an HLE handler calling
     * psp_dispatch() to re-enter guest code, which runs the *recompiled*
     * version and destroys this side's independence. The dispatch counter is
     * how that shows up afterwards.
     *
     * Afterwards is not always soon enough. The interpreter bounds itself with
     * an instruction budget, but that budget does not cover time spent inside
     * an HLE handler — and a handler that re-enters guest code can land in a
     * recompiled function that never returns. The interpreter then never gets
     * its own loop back and the budget is never consulted. So the wall-clock
     * watchdog has to cover this side too, not just the recompiled run. */
    phase("interp-start");
    const uint64_t dispatch_before = psp_dispatch_calls();
    const uint64_t miss_before     = g_miss_count;
    g_trapped = 0;
    if (sigsetjmp(g_trap, 1) == 0) {
        /* Service re-entry rather than bounding it. A firmware handler that
         * calls back into guest code now runs that code *interpreted*, nested
         * under this run and charged against its budget -- so the run stays
         * independent of the recompiled side and stays bounded. Previously the
         * only options were to run recompiled code inside the interpreter's
         * run, or throw the function away; this was the largest skip category
         * on the module by a wide margin. */
        psp_interp_service_dispatch(1);
        watchdog_arm_us(WATCHDOG_INTERP_USEC);
        psp_interp_run(&it);
        watchdog_disarm();
        psp_interp_service_dispatch(0);
    } else {
        watchdog_disarm();
        psp_interp_service_dispatch(0);
    }
    phase("interp-done");
    if (g_trapped == 4) return R_SKIP_REENTRY;
    if (g_trapped == 2) return R_HANG_INTERP;
    if (g_trapped == 3) return R_FAULT;
    if (g_trapped)      return R_SKIP_TRAP;
    /* A dispatch during the interpreter run is no longer grounds to skip: the
     * hook above ran it interpreted, so independence is intact. A dispatch
     * *miss* still is -- nothing ran, and the two sides did different work. */
    (void)dispatch_before;
    if (g_miss_count != miss_before) return R_SKIP_REENTRY;
    if (it.status != I_OK_RETURN) {
        uint32_t hot_n = 0;
        const uint32_t hot = psp_interp_hot_nid(&hot_n);
        if (it.status == I_BUDGET) {
            /* Report the loop, not the caller. The busiest address is the
             * innermost loop body, and the same handful of sites turn up under
             * thousands of different entry points -- a non-terminating leaf
             * poisons everything above it, so grouping by entry point counts
             * the same defect over and over. */
            uint32_t pc_n = 0;
            const uint32_t pc = want_profile ? psp_interp_hot_pc(&pc_n) : 0;
            /* One line per run, aggregated outside rather than tallied here:
             * the in-process tally has a fixed bucket count and silently drops
             * everything past it, which turns a long tail into a misleading
             * list of singletons. */
            printf("SPIN %08X pc=%08X n=%u nid=%08X nidn=%u\n",
                   addr, pc, pc_n, hot, hot_n);
            tally("interp: instruction budget exhausted");
            return R_SKIP_TRAP;
        }
        if (it.status == I_TRAP_VFPU || it.status == I_TRAP_INVALID) {
            a_insn bad;
            a_decode(psp_read32(it.fault_pc), it.fault_pc, &bad);
            char buf[64];
            snprintf(buf, sizeof buf, "interp: %s (%s)",
                     psp_interp_status_str(it.status), a_mnemonic(bad.op));
            tally(buf);
        } else {
            char buf[64];
            snprintf(buf, sizeof buf, "interp: %s", psp_interp_status_str(it.status));
            tally(buf);
        }
        return R_SKIP_TRAP;
    }

    /* Stack balance is the test for "was this address really callable?".
     *
     * Discovery splits on any address something points at, so a `function` can
     * begin in the middle of a real one — past the prologue that allocated the
     * frame. Entering there, the epilogue's `lw $ra, N($sp)` reads a slot no
     * prologue ever wrote, and the interpreter jumps to whatever garbage that
     * yields and runs on until it happens to reach the sentinel. The recompiled
     * side just returns off the end of its C body. The two then disagree about
     * everything, and none of it is a codegen bug.
     *
     * A well-formed function leaves $sp exactly as it found it. Anything else
     * was not independently callable, so the comparison is meaningless rather
     * than failing. (psprecomp makes the same check for the same reason —
     * see PSP_SP_CHECK in the generated code.) */
    if (psp_cpu.r[PSP_REG_SP] != g_stack_top) return R_SKIP_UNBALANCED;

    phase("snap-si");
    snap_take(si);

    phase("recomp-start");
    /* --- recompiled --- */
    const uint64_t miss_after_interp = g_miss_count;
    snap_restore(base);
    reset_hle();
    g_trapped = 0;
    if (sigsetjmp(g_trap, 1) == 0) {
        watchdog_arm();
        fn();
        watchdog_disarm();
    } else {
        watchdog_disarm();
    }
    phase("recomp-done");
    if (g_trapped == 2) return R_HANG;
    if (g_trapped == 3) return R_FAULT;
    if (g_trapped) {
        char buf[64];
        snprintf(buf, sizeof buf, "recomp: %s", g_trap_what ? g_trap_what : "trap");
        tally(buf);
        return R_SKIP_TRAP;
    }
    phase("snap-sr");
    snap_take(sr);

    const int diffs = compare(si, sr, addr, verbose);
    if (!diffs) return R_MATCH;

    /* A dispatch miss during the recompiled run explains a divergence without
     * implicating the emitter. The interpreter follows an indirect jump to
     * whatever it computes; the recompiled side hands the same address to
     * psp_dispatch(), which does nothing when discovery never registered it.
     * The two then legitimately do different work, and the defect is in
     * discovery's coverage, not in the code that was generated. Worth counting
     * separately -- the fix is a different one. */
    if (g_miss_count != miss_after_interp) {
        if (verbose)
            printf("  %08X  (dispatch miss during the recompiled run: discovery gap)\n", addr);
        return R_DIFF_MISS;
    }
    return R_DIFF;
}

/* -------------------------------------------------------------------------- */

int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr,
            "oracle_diff <module.elf> --funcs LIST  [--limit N] [--prefix] [--verbose]\n"
            "oracle_diff <module.elf> --text-walk   [--limit N] [--verbose]\n"
            "oracle_diff <module.elf> --from ADDR   [--verbose]\n"
            "\n"
            "Runs each function through the interpreter and the recompiled C and\n"
            "reports disagreements.\n"
            "\n"
            "  --funcs LIST  the work-list: function entries, as printed by\n"
            "                `allegrexrecomp funcs <elf> --list`. This is what\n"
            "                scripts/05-oracle.sh generates and passes.\n"
            "  --text-walk   instead, walk .text on 4-byte boundaries and test\n"
            "                every address the dispatch table resolves. That set is\n"
            "                mostly interior labels rather than entries, so it\n"
            "                answers the label-coverage question, not the codegen\n"
            "                one.\n"
            "  --limit N     cap attempts; 0 means no cap. A capped --funcs run\n"
            "                strides the whole list rather than taking a prefix.\n"
            "  --prefix      take the first N of the work-list instead of striding.\n"
            "  --from ADDR   test one address and nothing else.\n");
        return 2;
    }
    const char *path = argv[1];
    long limit = 2000;
    uint32_t only = 0; int have_only = 0;
    const char *funcs_path = NULL;
    int verbose = 0, want_text_walk = 0, want_prefix = 0;
    for (int i = 2; i < argc; i++) {
        if (!strcmp(argv[i], "--limit") && i + 1 < argc) limit = strtol(argv[++i], NULL, 0);
        else if (!strcmp(argv[i], "--from") && i + 1 < argc) { only = (uint32_t)strtoul(argv[++i], NULL, 0); have_only = 1; }
        else if (!strcmp(argv[i], "--verbose")) verbose = 1;
        else if (!strcmp(argv[i], "--phase")) g_phase_trace = 1;
        else if (!strcmp(argv[i], "--profile")) want_profile = 1;
        else if (!strcmp(argv[i], "--funcs") && i + 1 < argc) funcs_path = argv[++i];
        else if (!strcmp(argv[i], "--text-walk")) want_text_walk = 1;
        else if (!strcmp(argv[i], "--prefix")) want_prefix = 1;
        else { fprintf(stderr, "unknown option %s\n", argv[i]); return 2; }
    }

    /* Which work-list to use is an explicit choice now, with no default.
     *
     * It used to default to the .text walk, which reads as "test everything"
     * and is not. The dispatch table holds interior labels as well as function
     * entries -- roughly five labels for every entry on this module, about
     * 59,000 dispatch registrations against about 16,000 functions -- so most
     * of what the walk attempts was never independently callable, and the
     * $sp-balance check throws it away only after running it. Worse, at that
     * table density (under a tenth of .text words resolve) a --limit of 5,000
     * stops a few hundred KB in: single-digit percent of a 3 MB .text,
     * all of it at the low end. Two
     * runs straddling an emitter change that reclaimed 171 functions produced
     * byte-identical reports for exactly that reason -- every function the
     * change touched was past the window.
     *
     * The walk still answers the question it was written for, which is how much
     * of the dispatch table is reachable at all. It just should not be the
     * thing that runs when nobody said which they wanted. */
    if (!funcs_path && !want_text_walk && !have_only) {
        fprintf(stderr,
            "no work-list selected.\n"
            "  --funcs LIST   function entries (`allegrexrecomp funcs <elf> --list`)\n"
            "  --text-walk    every dispatch-table address in .text, labels included\n"
            "  --from ADDR    a single function\n");
        return 2;
    }
    if (funcs_path && want_text_walk) {
        fprintf(stderr, "--funcs and --text-walk are different work-lists; pick one\n");
        return 2;
    }

    psp_blob b;
    if (psp_blob_read(path, &b) != 0) { fprintf(stderr, "cannot read %s\n", path); return 1; }
    elf_info e;
    if (elf_parse(b.data, b.size, &e) != 0) { fprintf(stderr, "not an ELF/PRX\n"); return 1; }
    if (psp_mem_init() != 0) { fprintf(stderr, "no guest memory\n"); return 1; }

    /* Load *and relocate*. Without the relocation pass every cross-segment
     * pointer in the module reads as a small number, usually zero, and code
     * that walks a table from such a pointer runs off into .text and never
     * terminates -- on this module that shape alone was 58% of all runs that
     * failed to finish. It affects both sides equally, so it never showed up
     * as a divergence, only as runs the harness had to throw away. */
    psp_load_info li;
    if (psp_load_module(&b, &e, &li) != 0) {
        fprintf(stderr, "cannot load module\n"); return 1;
    }
    const uint32_t lo = li.lo, hi = li.hi;

    g_module_lo   = lo;
    g_module_size = hi - lo;
    g_module_host = psp_mem_ptr(lo, 1);
    if (!g_module_host) { fprintf(stderr, "module mapping failed\n"); return 1; }

    g_stub_lo = e.stub_addr;
    g_stub_hi = e.stub_addr + e.stub_size;

    signal(SIGALRM, watchdog);
    install_fault_handler();
    psp_set_miss_handler(note_miss);
    psp_recomp_register();
    psp_hle_init();

    /* No real threads. A function under test that calls sceKernelStartThread
     * would otherwise run it concurrently, on a host thread that shares the one
     * global register file -- so the comparison stops being about codegen and
     * starts being about scheduling, and the run hangs outright when the
     * spawned thread never hands the token back. Observed exactly that: two
     * threads in futex_wait, ten hours elapsed and ten seconds of CPU. */
    psp_sched_set_threading(0);
    /* Millions of firmware calls follow, and the watchdog longjmps out of a
     * signal handler -- an fprintf interrupted mid-call would leave stdio's
     * lock held and deadlock the next one. See psp_hle_set_quiet in hle.c. */
    psp_hle_set_quiet(1);

    /* Profiling costs an increment on every interpreted instruction and a
     * multi-megabyte clear per function. It earned that once -- it is what
     * found the relocation bug -- but the question is answered, so it is opt-in
     * now via --profile. */
    if (want_profile) psp_interp_profile(g_module_lo, g_module_size / 4);

    /* Give the interpreter the same firmware boundary the recompiled stubs
     * have. Without this every function reaching an import is uncomparable. */
    int nimp = 0;
    psp_module_info mi;
    if (e.modinfo_size && psp_modinfo_parse(b.data, b.size, e.modinfo_offset, &mi) == 0) {
        const uint32_t bias = e.nsegments ? e.seg[0].offset - e.seg[0].addr : 0;
        int n = psp_collect_imports(b.data, b.size, &mi, bias, NULL, 0);
        if (n > 0) {
            psp_import_entry *imp = malloc((size_t)n * sizeof *imp);
            psp_interp_import *tbl = malloc((size_t)n * sizeof *tbl);
            if (imp && tbl) {
                n = psp_collect_imports(b.data, b.size, &mi, bias, imp, n);
                for (int i = 0; i < n; i++) { tbl[i].addr = imp[i].addr; tbl[i].nid = imp[i].nid; }
                nimp = psp_interp_set_imports(tbl, n);
            }
            free(imp);
        }
    }

    snapshot base, si, sr;
    snap_alloc(&base); snap_alloc(&si); snap_alloc(&sr);
    snap_alloc(&g_pristine);
    snap_take(&g_pristine);

    printf("module:   %s\n", path);
    printf("mapped:   0x%08X + %u bytes\n", lo, g_module_size);
    printf("relocs:   %d applied\n", li.nrelocs);
    printf("stubs:    0x%08X..0x%08X (%u bytes, %d routed to HLE)\n",
           g_stub_lo, g_stub_hi, e.stub_size, nimp);
    printf("text:     0x%08X + %u bytes\n", e.text_addr, e.text_size);

    long attempted = 0, match = 0, diff = 0, unregistered = 0;
    long skip_import = 0, skip_trap = 0, skip_nofn = 0, hang = 0, skip_unbal = 0, skip_reentry = 0, hang_interp = 0, faults = 0, diff_miss = 0, skip_stub = 0;

    /* `limit` bounds *attempts*, not successful comparisons. Bounding successes
     * instead makes the loop unbounded whenever most functions are skipped —
     * which is the common case here, since anything touching an import is
     * excluded — and the harness then grinds through the whole work-list
     * running each one to its instruction budget first. `--limit 0` lifts the
     * bound entirely, which is how a full-corpus run is asked for. */
    const uint32_t text_lo = e.text_addr, text_hi = e.text_addr + e.text_size;

    /* The work-list: function entries from `allegrexrecomp funcs --list`.
     *
     * Only the addresses are read. Everything else the listing prints -- the
     * header block, the per-library import counts, the shape summary -- either
     * starts with something other than `0x` or is indented past it, so the
     * filter is the address column itself rather than a line count. */
    uint32_t *worklist = NULL;
    long nwork = 0;
    if (funcs_path) {
        FILE *lf = fopen(funcs_path, "r");
        if (!lf) { fprintf(stderr, "cannot read %s\n", funcs_path); return 1; }
        long cap = 4096;
        worklist = malloc((size_t)cap * sizeof *worklist);
        char line[256];
        while (worklist && fgets(line, sizeof line, lf)) {
            unsigned a;
            if (sscanf(line, " 0x%x", &a) != 1) continue;
            if (nwork == cap) {
                cap *= 2;
                uint32_t *bigger = realloc(worklist, (size_t)cap * sizeof *worklist);
                if (!bigger) break;
                worklist = bigger;
            }
            worklist[nwork++] = a;
        }
        fclose(lf);
        if (!nwork) { fprintf(stderr, "no function entries in %s\n", funcs_path); return 1; }
    }

    /* Sample the whole list rather than a prefix of it.
     *
     * Taking the first N makes a limited run *positional*: it reports on the
     * low end of the module and says nothing about the rest, while presenting
     * itself as a corpus result. That is not hypothetical — it is why two runs
     * across a change that reclaimed 171 functions came out byte-identical.
     *
     * Striding spends the same budget across the whole address range, so a
     * limited run is representative and two runs at the same limit still line
     * up entry for entry. Round the stride *up*, so it reaches the last entry
     * instead of exhausting the budget at nine tenths of the way through; the
     * cost is that `--limit 5000` on ~16,000 entries strides by 4 and selects
     * about 4,100 rather than exactly 5,000. The header says which, so nobody
     * has to infer it -- and so this comment does not have to carry a count
     * that changes every time discovery is rebuilt. */
    long stride = 1;
    if (worklist && limit > 0 && !want_prefix && nwork > limit)
        stride = (nwork + limit - 1) / limit;

    /* --from overrides whatever work-list was built, so do not describe one:
     * a header advertising the whole entry list above a run that tested a single
     * address is exactly the sort of thing this change exists to stop. */
    if (have_only) {
        printf("only:     0x%08X (single function; work-list ignored)\n", only);
    } else if (worklist) {
        long nsel;
        if (stride > 1)                      nsel = (nwork + stride - 1) / stride;
        else if (limit > 0 && limit < nwork) nsel = limit;      /* --prefix */
        else                                 nsel = nwork;
        printf("worklist: %ld function entries from %s\n", nwork, funcs_path);
        if (stride > 1)
            printf("sample:   %ld of %ld, every %ld across 0x%08X..0x%08X\n",
                   nsel, nwork, stride, worklist[0], worklist[(nsel - 1) * stride]);
        else if (nsel < nwork)
            printf("sample:   %ld of %ld, the first N (--prefix) -- 0x%08X..0x%08X\n",
                   nsel, nwork, worklist[0], worklist[nsel - 1]);
        else
            printf("sample:   all %ld -- 0x%08X..0x%08X\n",
                   nwork, worklist[0], worklist[nwork - 1]);
    } else if (want_text_walk) {
        /* Say plainly that this one *is* positional. It walks addresses in
         * order and stops when the budget runs out, so a limited walk is a
         * report on the bottom of .text and nothing else. */
        printf("worklist: .text walk from 0x%08X, every 4 bytes, interior labels included\n",
               text_lo);
        if (limit > 0)
            printf("sample:   first %ld resolved addresses -- positional, not representative\n",
                   limit);
    }
    printf("---\n");

    for (long wi = 0; ; wi++) {
        uint32_t a;
        if (have_only)      { if (wi) break; a = only; }
        else if (worklist)  {
            const long idx = wi * stride;
            if (idx >= nwork) break;
            if (limit > 0 && attempted >= limit) break;
            a = worklist[idx];
        }
        else {
            a = text_lo + (uint32_t)wi * 4;
            if (a >= text_hi) break;
            if (limit > 0 && attempted >= limit) break;
        }
        /* Not in the dispatch table.
         *
         * On the .text walk this is the ordinary case -- most words in .text
         * are not the start of anything -- and counting it says nothing. On the
         * entry list it is a finding: discovery named a function the emitter
         * never registered, so there is no recompiled side to compare against.
         * Silently dropping those makes `attempted` fall short of the sample
         * size with no stated reason, which is the same kind of quiet
         * misreporting the positional sample was. */
        if (!psp_lookup(a)) { unregistered++; continue; }
        /* Import thunks are in .text and land in the discovered function list,
         * but they are not functions -- they are the firmware boundary. The
         * interpreter intercepts them into HLE and the recompiled side has a
         * generated stub; comparing the two as if they were guest code
         * measures nothing. */
        if (a >= g_stub_lo && a < g_stub_hi) { skip_stub++; continue; }
        attempted++;
        switch (check_one(a, &base, &si, &sr, verbose)) {
        case R_MATCH:        match++; break;
        case R_DIFF:         diff++;  break;
        case R_SKIP_IMPORT:  skip_import++; break;
        case R_SKIP_TRAP:    skip_trap++;   break;
        case R_SKIP_NOFN:    skip_nofn++;   break;
        case R_HANG:         hang++;        break;
        case R_SKIP_UNBALANCED: skip_unbal++; break;
        case R_SKIP_REENTRY: skip_reentry++; break;
        case R_HANG_INTERP:  hang_interp++;  break;
        case R_FAULT:        faults++;       break;
        case R_DIFF_MISS:    diff_miss++;    break;
        }
        if ((attempted % 200) == 0) {
            printf("... %ld attempted, %ld compared\n", attempted, match + diff);
            fflush(stdout);
        }
    }

    printf("---\n");
    printf("attempted: %ld functions\n", attempted);
    printf("compared:  %ld\n", match + diff + diff_miss);
    printf("  match:  %ld\n", match);
    printf("  differ: %ld\n", diff);
    printf("  differ (dispatch miss -- discovery gap, not codegen): %ld\n", diff_miss);
    printf("skipped:\n");
    printf("  HLE re-entry:    %ld  (handler called back into guest code)\n", skip_reentry);
    printf("  trapped:         %ld  (unimplemented instruction on one side)\n", skip_trap);
    printf("  recomp hung:     %ld  (interpreter returned; recompiled C did not)\n", hang);
    printf("  interp hung:     %ld  (watchdog fired inside the interpreter run)\n", hang_interp);
    printf("  unbalanced $sp:  %ld  (entry was not independently callable)\n", skip_unbal);
    printf("  host fault:      %ld  (SIGSEGV/SIGBUS, usually host stack exhaustion)\n", faults);
    printf("  import thunk:    %ld  (firmware boundary, not guest code)\n", skip_stub);
    if (worklist)
        printf("  unregistered:    %ld  (entry discovery found but the emitter did not register)\n",
               unregistered);
    if (psp_interp_nest_refused())
        printf("  re-entry refused: %llu  (nesting limit; a guest callback did not run)\n",
               (unsigned long long)psp_interp_nest_refused());
    tally_dump();

    psp_mem_free();
    psp_blob_free(&b);
    return diff ? 1 : 0;
}
