#!/usr/bin/env python3
"""geprobe 23 (scene 145, risky, last): a patch division of 0.

geprobe 13 (scenes 80-81) found that the GE takes 7 bits of each PATCHDIVISION field,
draws divisions 1 to 64, and hangs at 65 to 127 (nothing of the patch, nothing more of
the list, until sceGeBreak). 0 was never posed: psprecomp draws it as 1. Each case
here is its own list (the FLUSH op runs it and logs its GE time; a hung one is broken
off after a second by ge_wait, which says so in the log), and after the patch the same
list draws a small through-mode marker square, which is there only if the list went
on. The patches are 4 x 4 Beziers and 5 x 5 splines under the probes' perspective,
each in its own cell, drawn as triangles, lines or points; the controls at divisions
1 x 1 are drawn too, for what "as 1" would look like.

    pzero23.py emit [OUT.inc]        write c23z_data.inc
    pzero23.py sums DUMPDIR          the logged CRCs against this stream
    pzero23.py compare DUMPDIR [PCDIR]   per case: GE time, marker, pixels, against psprecomp
    pzero23.py check                 the cases
"""
import sys, os, math, struct, zlib, re
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import colour14 as C
import plines21 as PL
from colour14 import XS, f32, bf, FMT_CV3D, FMT_CV2D, GU_FLAT, GU_SMOOTH, begin

GU_POINTS, GU_LINE_STRIP, GU_TRIANGLE_STRIP, GU_SPRITES = 0, 2, 4, 6
PRIMS = {'tri': GU_TRIANGLE_STRIP, 'line': GU_LINE_STRIP, 'point': GU_POINTS}

# (kind, du, dv, prim): the controls first, then 0 in each place
CASES = [
    ('b', 1, 1, 'tri'), ('b', 0, 0, 'tri'), ('b', 0, 3, 'tri'), ('b', 3, 0, 'tri'),
    ('b', 1, 1, 'line'), ('b', 0, 0, 'line'), ('b', 0, 0, 'point'), ('b', 64, 0, 'tri'),
    ('s', 1, 2, 'tri'), ('s', 0, 2, 'tri'), ('s', 2, 0, 'line'), ('s', 0, 0, 'point'),
]
CELLS = [(c, r) for r in range(3) for c in range(4)]

def patch(kind, cell, r):
    cu = cv = 4 if kind == 'b' else 5
    c, row = cell
    x0, y0 = 120 * c + 20, 90 * row + 15
    pts = []
    for j in range(cv):
        for i in range(cu):
            px = x0 + 80 * i / (cu - 1) + (r() % 9) - 4
            py = y0 + 56 * j / (cv - 1) + (r() % 9) - 4
            X, Y = PL.model_of(px, py)
            pts.append((f32(X), f32(Y), f32(-5.0 + ((r() % 100) / 100 - 0.5) * 0.4), 0xFF000000 | (r() & 0xFFFFFF)))
    return cu, cv, pts

def marker(k):
    """The case's marker: a 4 x 4 square below its cell, in through mode."""
    c, row = CELLS[k]
    x, y = 120 * c + 104, 90 * row + 80
    col = 0xFF000000 | (0x30 + 16 * k) << 8 | 0xF0
    return [dict(x=float(x), y=float(y), z=0.0, c=col), dict(x=float(x + 4), y=float(y + 4), z=0.0, c=col)]

def scene_ops():
    r = XS(0x14500001)
    ops = [begin()]
    for k, (kind, du, dv, prim) in enumerate(CASES):
        cu, cv, pts = patch(kind, CELLS[k], r)
        ops.append(('MATS', PL.PERSP, PL.ID, PL.ID))
        ops.append(('PATCH', 0 if kind == 'b' else 1, FMT_CV3D, cu, cv, 0, 0, PRIMS[prim], du, dv,
                    [dict(x=p[0], y=p[1], z=p[2], c=p[3]) for p in pts]))
        ops.append(('DRAW', GU_SPRITES, FMT_CV2D, marker(k), None))
        ops.append(('FLUSH', k))
    ops.append(('END', 0))
    return ops

SCENES = [(145, 'patchzero', 'patch division 0 (risky, own step, last)')]

def emit_scene():
    OP = C.OP
    w = []; vcrc = 0; nd = 0; nv = 0
    def op(name, args):
        w.append(OP[name] << 24 | len(args)); w.extend(a & 0xFFFFFFFF for a in args)
    body = []
    for o in scene_ops():
        k = o[0]
        if k == 'BEGIN': body.append(('BEGIN', [o[1], o[2]]))
        elif k == 'END': body.append(('END', [o[1]]))
        elif k == 'MATS': body.append(('MATS', [7] + C.mem16(o[1]) + C.mem16(o[2]) + C.mem16(o[3])))
        elif k == 'FLUSH': body.append(('FLUSH', [o[1]]))
        elif k == 'PATCH':
            kind, vtype, cu, cv, ue, ve, prim, du, dv, verts = o[1:]
            vb = C.vbytes(vtype, verts)
            vcrc = zlib.crc32(vb, vcrc); nd += 1; nv += cu * cv
            body.append(('PATCH', [kind, vtype, cu, cv, ue, ve, prim, du, dv, len(vb)] + C.words(vb)))
        elif k == 'DRAW':
            prim, vtype, verts = o[1], o[2], o[3]
            vb = C.vbytes(vtype, verts)
            vcrc = zlib.crc32(vb, vcrc); nd += 1; nv += len(verts)
            body.append(('DRAW', [prim, vtype, len(verts), len(vb), 0] + C.words(vb)))
        else: raise ValueError(k)
    op(*body[0])
    op('SUMS', [nd, nv, vcrc & 0xFFFFFFFF])
    for b in body[1:]: op(*b)
    return w, nd, nv, vcrc & 0xFFFFFFFF

def emit(path):
    out = ['/* Generated by pzero23.py emit: geprobe 23 scene 145 (patch division 0) as a',
           ' * command stream for c14_run() (colour14.py\'s format, with PATCH and FLUSH).  Do not',
           ' * edit; change pzero23.py and run it again. */']
    n, name, title = SCENES[0]
    w, nd, nv, vc = emit_scene()
    crc = zlib.crc32(struct.pack(f'<{len(w)}I', *w)) & 0xFFFFFFFF
    out.append(f'\n/* scene {n} {name}: {nd} draws, {nv} vertices, vertex crc {vc:08X},'
               f' {len(w)} words, stream crc {crc:08X} */')
    out.append(f'static const w32 C23Z_S0[{len(w)}] = {{')
    for i in range(0, len(w), 8): out.append(' ' + ' '.join(f'0x{x:08X}u,' for x in w[i:i + 8]))
    out.append('};')
    out.append('\nstatic const struct c14_step C23Z_STEPS[] = {')
    out.append(f'    {{ {n}, "{name}", "{title}", C23Z_S0, {len(w)} }},')
    out.append('};\n#define C23Z_NSTEPS ((int)(sizeof C23Z_STEPS / sizeof C23Z_STEPS[0]))\n')
    text = '\n'.join(out)
    if not os.path.exists(path) or open(path).read() != text: open(path, 'w').write(text)
    return [(dict(num=n, name=name, title=title), len(w), nd, nv, vc, crc)]

def sums(dumpdir):
    import tempfile
    log = open(os.path.join(dumpdir, 'geprobe.txt')).read()
    ok = True
    with tempfile.TemporaryDirectory() as td:
        for sc, n, nd, nv, vc, crc in emit(os.path.join(td, 'c23z.inc')):
            m = re.search(rf'scene {sc["num"]}: .*?\n\s+(\d+) draws, (\d+) vertices, '
                          rf'vertex crc ([0-9A-F]+), stream crc ([0-9A-F]+)', log)
            want = (str(nd), str(nv), f'{vc:08X}', f'{crc:08X}')
            good = bool(m) and m.groups() == want; ok &= good
            print(f'scene {sc["num"]} {sc["name"]}: ' + ('log MATCHES' if good else
                  f'log DIFFERS: {m.groups() if m else "no SUMS line"} against {want}'))
    print('all CRCs match' if ok else 'CRC PROBLEMS: do not read the pixels')
    return ok

def frame(d): return np.fromfile(os.path.join(d, 'ge_145_patchzero.raw'), '<u4').reshape(272, 480) & 0xFFFFFF

def compare(dumpdir, pcdir=None):
    log = open(os.path.join(dumpdir, 'geprobe.txt')).read()
    m = re.search(r'scene 145:.*?(?=\n\[|\Z)', log, re.S)
    print(m.group(0) if m else 'no scene 145 in the log')
    H = frame(dumpdir); P = frame(pcdir) if pcdir else None
    for k, case in enumerate(CASES):
        c, row = CELLS[k]
        box = (slice(90 * row, 90 * row + 78), slice(120 * c, 120 * c + 102))
        mk = marker(k)[0]
        has = bool(H[int(mk['y']) + 1, int(mk['x']) + 1])
        line = f'case {k} {case}: marker {"drawn" if has else "absent"}, {int((H[box] != 0).sum())} patch pixels'
        if P is not None: line += f'; psprecomp {int((P[box] != 0).sum())}, {int((H[box] != P[box]).sum())} differ'
        print(line)

def check():
    for k, c in enumerate(CASES): print(k, c, CELLS[k])

def main(argv):
    if len(argv) < 2: print(__doc__); return 2
    cmd = argv[1]
    if cmd == 'emit':
        for sc, n, nd, nv, vc, crc in emit(argv[2] if len(argv) > 2 else os.path.join(HERE, 'c23z_data.inc')):
            print(f'scene {sc["num"]} {sc["name"]}: {nd} draws, {nv} vertices, vertex crc {vc:08X}, {n} words, stream crc {crc:08X}')
        return 0
    if cmd == 'sums': return 0 if sums(argv[2]) else 1
    if cmd == 'compare': compare(argv[2], argv[3] if len(argv) > 3 else None); return 0
    if cmd == 'check': check(); return 0
    print(__doc__); return 2

if __name__ == '__main__':
    sys.exit(main(sys.argv))
