#!/usr/bin/env python3
"""geprobe 18 (scene 120): the lighting's 1/sqrt, every input read whole.

geprobe 17 found the GE's 1/sqrt to be a table like 1/w's: 128 entries for each parity
of the exponent, a value V and a slope S each, indexed by the 16-bit significand's top 7
bits after the leading one and interpolated by the next 8, l:
    q = (128 V - S l - 1) >> 8,   1/sqrt(s) = q 2^-16 2^-(E - p)/2,   s = sig 2^(E - 15)
(lights17.py GE_RSQ, ge.c ge_rsq_tab). Its readings pinned 219 entries; 37 still allowed
more than one (V, S). Set 19 (fw 6.60) answered: with all 256 outputs of each entry, one
(V, S) fits each, two of them not what set 18 chose, and every entry is a formula:
V = floor(2^17/sqrt(knot)) + 1 and S = 2 floor(c/4), c the exact chord to the next knot
(rsq18.formula). The input is always a 16-bit number (a GE sum, L.L, cut to 16
bits), so there are 65536 of them in [1, 4), and the table repeats by 4. This scene
reads all of them: for each s, a light at (px, py, 1) over a vertex at the origin with
D = +z, px and py chosen so that the GE's L.L (patch13 ge_sum) is s exactly, so the
spot's L.D is L's normalised z, 1/sqrt(s) itself. The probe searches the spot cutoff on
the PSP as scene 115 does (main.c l18_search), in three chunks of slots, each from a
bracket of +-32 codes around the current table's value (6 halvings and two checks).

    rsq18.py emit [OUT.inc]        write l18_data.inc (px, py and the predicted code each)
    rsq18.py sums DUMPDIR          the logged CRCs against these inputs
    rsq18.py compare DUMPDIR       every q against the table; per entry, the (V, S) that fit
"""
import sys, os, math, struct, zlib, re
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import patch13 as P13
import lights17 as L

N = 65536
CHUNKS = 3
BRACKET = 32

def s_of(px, py):
    """The GE's L.L for L = (px, py, 1) (vertex path ge_mul/ge_sum, as set 18 confirmed)."""
    return P13.ge_sum([P13.ge_mul(px, px), P13.ge_mul(py, py), P13.ge_mul(1.0, 1.0)])

def target(k):
    """Input k: parity p = k >> 15 (s in [1,2) or [2,4)), significand 32768 + (k & 0x7FFF)."""
    p, n = k >> 15, k & 0x7FFF
    return (32768 + n) / 32768 * (2.0 if p else 1.0)

def f16(v):
    """v cut to 16 significant bits (exact as a GE command or vertex float)."""
    return L.f24(v)

def neighbours(v, k):
    """v and its k 16-bit neighbours either side (v > 0)."""
    m, e = math.frexp(v); sig = int(m * 65536)
    return [math.ldexp(sig + d, e - 16) for d in range(-k, k + 1) if 32768 <= sig + d < 65536]

def find_p(s):
    """16-bit (px, py) with s_of(px, py) == s, py as small as can be."""
    rest = s - 1.0
    if rest == 0: return 0.0, 0.0
    for py in [0.0] + [math.ldexp(j, -e) for e in (8, 7, 6, 5, 4) for j in range(1, 16)]:
        r2 = rest - py * py
        if r2 <= 0: continue
        for px in neighbours(f16(math.sqrt(r2)), 4):
            if s_of(px, py) == s: return px, py
    return None

# The table the probe shipped with (set 18's): GE_RSQ but for the two entries set 19 corrected.
# The search brackets, and so the probe's input CRC, are centred on it; keep it as it was.
SHIPPED = {(0, 92): (99979, 113), (0, 100): (98209, 107)}

def predicted(s):
    """Set 18's table's 1/sqrt(s), as the cutoff code the search should find."""
    m, e = math.frexp(s); sig = int(m * 65536); E = e - 1
    p, t, l = E & 1, (sig & 0x7FFF) >> 8, sig & 0xFF
    V, S = SHIPPED.get((p, t), L.GE_RSQ[p][t])
    return L.code(P13.ge_cut(((128 * V - S * l - 1) >> 8) / 65536 * 2.0 ** (-(E - p) // 2)))

_G = []
def geometries():
    if not _G:
        miss = 0
        for k in range(N):
            s = target(k)
            pp = find_p(s)
            if pp is None: miss += 1; pp = (float('nan'), 0.0)
            _G.append((pp[0], pp[1], predicted(s) if pp[0] == pp[0] else 0))
        if miss: raise SystemExit(f'{miss} inputs with no (px, py)')
    return _G

def chunk_bounds():
    per = (N + CHUNKS - 1) // CHUNKS
    return [(c * per, min(N, (c + 1) * per)) for c in range(CHUNKS)]

def words():
    out = []
    for px, py, pc in geometries(): out += [L.bf(px), L.bf(py), pc]
    return out

def geo_crc():
    w = words(); return zlib.crc32(struct.pack(f'<{len(w)}I', *w)) & 0xFFFFFFFF

def emit(path):
    w = words()
    out = ['/* Generated by rsq18.py emit: geprobe 18 scene 120, the lighting\'s 1/sqrt at every',
           ' * 16-bit input in [1, 4). Per input: px and py (float bits) for a light at',
           ' * (px, py, 1) over a vertex at the origin, and the cutoff code the current table',
           ' * predicts. Do not edit; change rsq18.py and run it again. */',
           f'\n#define L18_N {N}', f'#define L18_CHUNKS {CHUNKS}', f'#define L18_BRACKET {BRACKET}',
           f'/* input crc {geo_crc():08X} */', f'static const w32 L18_GEO[{N}][3] = {{']
    for i in range(0, len(w), 3): out.append(f'    {{ 0x{w[i]:08X}u, 0x{w[i + 1]:08X}u, 0x{w[i + 2]:06X}u }},')
    out.append('};\n')
    text = '\n'.join(out)
    if not os.path.exists(path) or open(path).read() != text: open(path, 'w').write(text)

def read(dumpdir):
    raw = np.fromfile(os.path.join(dumpdir, 'ge_120_rsqfull.bin'), '<u4').reshape(-1, 2)
    return [(int(a) & 0xFFFFFF, int(a) >> 24, int(b)) for a, b in raw]

def sums(dumpdir):
    log = open(os.path.join(dumpdir, 'geprobe.txt')).read()
    m = re.search(r'scene 120: .*?\n\s+(\d+) inputs, input crc ([0-9A-F]+)', log)
    want = (str(N), f'{geo_crc():08X}')
    ok = bool(m) and m.groups() == want
    print('scene 120 rsqfull: ' + ('log MATCHES' if ok else f'log DIFFERS: {m.groups() if m else "no line"} against {want}'))
    return ok

def q_of(V, S, l): return (128 * V - S * l - 1) >> 8

def compare(dumpdir):
    G = geometries(); R = read(dumpdir)
    flagged = sum(1 for r in R if r[1])
    same = sum(1 for (px, py, pc), r in zip(G, R) if r[0] == pc and not r[1])
    print(f'120 rsqfull: {N} inputs, {flagged} flagged, {same} as set 18\'s table predicts')
    # each input's q, from its code: x = q/65536 for s in [1, 4)
    fits = {}; nofit = []
    for p in (0, 1):
        for t in range(128):
            qs = []
            for l in range(256):
                k = (p << 15) | (t << 8) | l
                code = R[k][0]
                qs.append(round(L.uncode(code) * 65536))
            V0, S0 = SHIPPED.get((p, t), L.GE_RSQ[p][t])
            sols = [(V, S) for V in range(V0 - 8, V0 + 9) for S in range(max(0, S0 - 8), S0 + 9)
                    if all(q_of(V, S, l) == qs[l] for l in range(256))]
            fits[(p, t)] = sols
            if not sols: nofit.append((p, t))
    from collections import Counter
    print('   entries with a (V, S) that fits all 256 inputs:', sum(1 for v in fits.values() if v), 'of 256;',
          'solutions per entry', sorted(Counter(len(v) for v in fits.values()).items()))
    changed = [(k, L.GE_RSQ[k[0]][k[1]], v) for k, v in fits.items() if v and tuple(L.GE_RSQ[k[0]][k[1]]) not in v]
    print('   entries whose (V, S) in lights17.GE_RSQ does not fit:', len(changed))
    for k, old, v in changed[:40]: print('     ', k, 'now', old, 'fits', v[:4])
    if nofit: print('   no (V, S) fits:', nofit[:20])
    fv = sum(1 for k, v in fits.items() if v and v[0] == formula(*k))
    print('   entries the formula gives (V = floor(2^17/sqrt(knot)) + 1, S = 2 floor(chord/4)):', fv, 'of 256')
    return fits

def formula(p, t):
    """Set 19's table as a rule: every one of its 256 entries is this."""
    ex = lambda k: 2**17 / math.sqrt(k)
    knot = (1 + t / 128) * (2 if p else 1)
    nxt = (1 + (t + 1) / 128) * (2 if p else 1)
    return math.floor(ex(knot)) + 1, 2 * math.floor((ex(knot) - ex(nxt)) / 4)

def check():
    G = geometries()
    pys = sum(1 for px, py, pc in G if py)
    print(f'{N} inputs, all with a (px, py); {pys} need py; chunks {chunk_bounds()}')

def main(argv):
    if len(argv) < 2: print(__doc__); return 2
    cmd = argv[1]
    if cmd == 'emit':
        emit(argv[2] if len(argv) > 2 else os.path.join(HERE, 'l18_data.inc'))
        print(f'scene 120 rsqfull: {N} inputs, input crc {geo_crc():08X}'); return 0
    if cmd == 'sums': return 0 if sums(argv[2]) else 1
    if cmd == 'compare': compare(argv[2]); return 0
    if cmd == 'check': check(); return 0
    print(__doc__); return 2

if __name__ == '__main__':
    sys.exit(main(sys.argv))
