#!/usr/bin/env python3
"""Build the result mapping solely from controlled, recorded API observations."""
from pathlib import Path

root = Path(__file__).resolve().parent
rows = {}
for line in (root/'observed.txt').read_text().splitlines():
    kind, case, *values = [int(word, 16) for word in line.split()]
    rows[kind, case] = values

# Each selector names the original stimulus in probe.c. Read success/failure
# results are word 3; initialization rejections are direct API return values.
selectors = [
    ('SD_LOAD_ABSENT', (0, 0), 1), ('SD_READ_ABSENT', (0, 1), 1),
    ('SD_DELETE_ABSENT', (0, 3), 1),
    ('SD_LOAD_MISSING_FILE', (0, 7), 1), ('SD_READ_MISSING_FILE', (0, 8), 1),
    ('SD_LOAD_INVALID_DATA', (0, 19), 1), ('SD_READ_INVALID_DATA', (0, 20), 1),
    ('SD_INVALID_REQUEST', (2, 0), 0), ('SD_ALREADY_ACTIVE', (2, 1), 1),
]
lines = ['/* Generated by tests/provenance/savedata/derive.py from our probe stdout.',
         ' * Historical source exposure remains recorded in docs/PROVENANCE.md.',
         ' * Host I/O failures use the BSD SDK generic error, not unobserved',
         ' * per-operation utility error numbers. */', 'typedef enum {']
lines += ['    '+name+',' for name, _, _ in selectors]
lines += ['    SD_HOST_IO', '} sd_failure;',
          'static uint32_t sd_error(sd_failure failure) {',
          '    static const uint32_t results[] = {']
for name, key, field in selectors:
    value = rows[key][field]
    assert value & 0x80000000
    lines += [f'        0x{value:08x}u, /* {name}: kind {key[0]}, case {key[1]} */']
    print(f'{name}: 0x{value:08x}')
lines += ['        0x80020001u /* BSD PSPSDK SCE_KERNEL_ERROR_ERROR: host I/O policy */',
          '    };', '    return results[failure];', '}', '']
(root.parents[2]/'src/hle/savedata_results.h').write_text('\n'.join(lines))
