/* Generated by tests/provenance/disc/derive.py from our probe stdout. */
#define IO_DISC_SECTOR 2048
#define IO_DISC_FILE_MODE 0x216d
#define IO_DISC_DIR_MODE 0x116d
#define IO_DISC_FILE_ATTR 0x20
#define IO_DISC_DIR_ATTR 0x10
/* Every disc entry reports the same times: year 1900, month 1, the rest zero. */
#define IO_DISC_TIME_WORD0 0x0001076c
#define IO_DISC_PRIVATE_FILL 0xfefefefe
#define IO_ERROR_NOENT 0x80010002
#define IO_ERROR_BADF 0x80020323
#define IO_ERROR_NO_ASYNC 0x8002032a
#define IO_ERROR_ASYNC_BUSY 0x80020329
