/* Generated by tests/provenance/mpeg/derive.py from our probe stdout. */
#define MPEG_MEMSIZE 0x00010000u
#define MPEG_RINGBUFFER_PACKET 0x00000868u
#define MPEG_AVC_ES_SIZE 0x00000800u
#define MPEG_ATRAC_ES_SIZE 0x00000840u
#define MPEG_ATRAC_ES_OUT_SIZE 0x00002000u
#define MPEG_HANDLE_OFFSET 0x00000030u
#define MPEG_ES_SLOTS 0x00000002u
#define MPEG_STREAM_HANDLE_STEP 0x00000001u
#define PSMF_STREAM_OFFSET_OFF 0x00000008u
#define PSMF_STREAM_SIZE_OFF 0x0000000cu
#define SCE_MPEG_ERROR_NO_MEMORY 0x80610022u
#define SCE_MPEG_ERROR_NOT_YET_INIT 0x80618009u
#define SCE_MPEG_ERROR_INVALID_VALUE 0x806101feu
#define SCE_MPEG_ERROR_NO_DATA 0x80618001u
#define MPEG_ERROR_UNSUPPORTED_HEADER 0x80610002u
/* The stimuli vary the four bytes after the magic; the offset query
 * accepts this contiguous range of them and nothing else swept. */
#define PSMF_TAG_OFF 4
#define PSMF_TAG_FIRST "0012"
#define PSMF_TAG_LAST "0015"
