#!/usr/bin/env python3
"""Derive wire constants from this project's separately recorded API stimuli."""
from pathlib import Path
root=Path(__file__).resolve().parent
rows={}
for line in (root/'observed.txt').read_text().splitlines():
    kind, case, *values=map(lambda x:int(x,16),line.split())
    rows[kind,case]=values
stride=rows[2,1][0]
for case,packets in enumerate([0,1,2,3,17,64,-1,0x100000]):
    assert rows[2,case][0]==(packets*stride)&0xffffffff
offsets=[0,1,15,64]
handle_offset=rows[5,1][1]-0xa0000000
for case,offset in enumerate(offsets,1):
    assert rows[5,case][1]-0xa0000000-offset==handle_offset
assert rows[10,0]==[1] and rows[10,1]==[2] and rows[10,2]==[0]
# Lifecycle: ring construction and context creation succeed before any
# initialization call, and initialization answers zero on a repeated call.
assert rows[18,0]==[0,0,0xa0000000+handle_offset,3]
assert rows[1,0]==[0] and rows[1,1]==[0]

# Stream header queries. The stimuli place distinct big-endian words
# BASE+w*STEP at byte 4*w after the tag; the outputs identify which word each
# query reads. Storing the same words little-endian is refused.
BASE,STEP=0x00120000,0x800
def word_at(value):
    w,rem=divmod(value-BASE,STEP)
    assert rem==0 and 1<=w<32, hex(value)
    return 4*w
size_off=word_at(rows[19,0][1]);assert rows[19,0][0]==0
offset_off=word_at(rows[19,13][3]);assert rows[19,13][2]==0
assert size_off!=offset_off
assert rows[19,4][0]&0x80000000 and rows[19,4][2]&0x80000000
invalid=rows[15,0][0]
assert rows[15,1]==[invalid,0] and rows[19,3]==[invalid,0,invalid,0]
# The size query passes any size word through (0x400, zero) but refuses an
# offset word off a sector boundary; the offset query refuses zero as well.
assert rows[19,16][:2]==[0,0x400] and rows[19,8][:2]==[0,0]
assert rows[19,14]==[invalid,0,invalid,0] and rows[19,15][2:]==[invalid,0]
assert rows[19,11][2:]==[0,0x800] and rows[19,17][2:]==[0,0x7ffff800]
# The offset query also requires the four bytes after the magic to lie in a
# contiguous range: every swept tag inside it is accepted, every tag outside
# it, including the nearest neighbours, is refused with one distinct result
# and a zero output. Without such a tag the size query still answers.
tags=["0000","0001","0009","0010","0011","0012","0013","0014","0015","0016",
      "0017","0019","0020","0099","0100","1015","001A","0 15"]
accepted=[t for i,t in enumerate(tags) if rows[21,i]==[0,0x800]]
refused=[(t,rows[21,i]) for i,t in enumerate(tags) if t not in accepted]
first,last=min(accepted),max(accepted)
assert all(first<=t<=last for t in accepted)
assert all(not first<=t<=last and r[1]==0 for t,r in refused)
tag_error={r[0] for _,r in refused};assert len(tag_error)==1
tag_error=tag_error.pop()
assert f'{int(first)-1:04d}' in dict(refused) and f'{int(last)+1:04d}' in dict(refused)
assert rows[19,0][2]==tag_error and rows[19,10][2]==tag_error   # tag before alignment

# Stream handles lie outside the caller's storage; each registration answers
# one step above the last, and the recorded unregistrations recycle nothing.
assert rows[20,0][:3]==[0xffffffff]*3
step=rows[20,0][3]
assert rows[20,0][4]==2*step and rows[20,1]==[0xffffffff,3*step] and rows[20,2]==[0xffffffff,4*step]

values={
    'MPEG_MEMSIZE': rows[0,0][0], 'MPEG_RINGBUFFER_PACKET': stride,
    'MPEG_AVC_ES_SIZE': rows[14,1][5],
    'MPEG_ATRAC_ES_SIZE': rows[7,1][1], 'MPEG_ATRAC_ES_OUT_SIZE': rows[7,1][2],
    'MPEG_HANDLE_OFFSET': handle_offset, 'MPEG_ES_SLOTS': 2,
    'MPEG_STREAM_HANDLE_STEP': step,
    'PSMF_STREAM_OFFSET_OFF': offset_off, 'PSMF_STREAM_SIZE_OFF': size_off,
    'SCE_MPEG_ERROR_NO_MEMORY': rows[3,0][0],
    'SCE_MPEG_ERROR_NOT_YET_INIT': rows[5,0][2],
    'SCE_MPEG_ERROR_INVALID_VALUE': rows[15,0][0],
    'SCE_MPEG_ERROR_NO_DATA': rows[15,2][0],
    'MPEG_ERROR_UNSUPPORTED_HEADER': tag_error,
}
lines=['/* Generated by tests/provenance/mpeg/derive.py from our probe stdout. */']
for name,value in values.items():
    lines.append(f'#define {name} 0x{value:08x}u')
    print(f'{name}=0x{value:08x}')
lines.append('/* The stimuli vary the four bytes after the magic; the offset query')
lines.append(' * accepts this contiguous range of them and nothing else swept. */')
lines.append('#define PSMF_TAG_OFF 4')
lines.append(f'#define PSMF_TAG_FIRST "{first}"')
lines.append(f'#define PSMF_TAG_LAST "{last}"')
print(f'PSMF_TAG_FIRST={first} PSMF_TAG_LAST={last}')
(root.parents[2]/'src/hle/mpeg_observed.h').write_text('\n'.join(lines)+'\n')
